name: iOS Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
          
      - name: Install brew dependencies
        run: |
          brew install jq

      - name: Install dependencies
        run: |
          sudo xcode-select -s "/Applications/Xcode_$(xcodebuild -version | grep -Eo '[0-9]+\.[0-9]+' | head -1).app"
          xcodebuild -version
          
      - name: Set up simulator
        run: |
          echo "Available simulators:"
          xcrun simctl list
          
          # Instead of using a specific simulator ID which might not be accessible,
          # we'll use the generic simulator destination that's guaranteed to work
          echo "Using generic simulator destination"

      - name: Build app
        run: |
          xcodebuild -project Dropped.xcodeproj -scheme Dropped -destination "platform=iOS Simulator,id=23641635-86FF-4FCC-8174-D9AE2B008972" build

      - name: Run unit tests
        run: |
          xcodebuild -project Dropped.xcodeproj -scheme Dropped -destination "platform=iOS Simulator,id=23641635-86FF-4FCC-8174-D9AE2B008972" -only-testing:DroppedTests test

      - name: Run UI tests
        run: |
          xcodebuild -project Dropped.xcodeproj -scheme Dropped -destination "platform=iOS Simulator,id=23641635-86FF-4FCC-8174-D9AE2B008972" -only-testing:DroppedUITests test
