name: iOS Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: List available simulators
        run: |
          echo "Available simulators:"
          xcrun simctl list devices

      - name: Show build destinations
        run: |
          echo "Available build destinations:"
          xcodebuild -project Dropped.xcodeproj -scheme Dropped -showdestinations

      - name: Build app
        run: |
          xcodebuild -project Dropped.xcodeproj -scheme Dropped -destination 'platform=iOS Simulator,OS=latest' build

      - name: Run unit tests
        run: |
          xcodebuild -project Dropped.xcodeproj -scheme Dropped -destination 'platform=iOS Simulator,OS=latest' -only-testing:DroppedTests test

      - name: Run UI tests
        run: |
          xcodebuild -project Dropped.xcodeproj -scheme Dropped -destination 'platform=iOS Simulator,OS=latest' -only-testing:DroppedUITests test
